Algoritmo "ImparPar"
// 
   //Autor; Maria Eduarda Orsi

Var
   // Seção de Declarações das variáveis
      num:inteiro

Inicio
      // Seção de Comandos, procedimento, funções, operadores, etc...
          escreval ("Digite um valor: ")
          leia(num)

            se((num mod 2)=0)entao
            escreval("Este numero é par.")

            senao
            escreval("Este numero é impar.")
            fimse

Fimalgoritmo